products:
  get:
    tags:
      - Products
    summary: List all products
    description: Get a paginated list of all products. Can be filtered by category.
    operationId: listProducts
    parameters:
      - name: category
        in: query
        description: Filter products by category ID
        required: false
        schema:
          type: integer
          example: 1
      - name: page
        in: query
        description: Page number for pagination
        required: false
        schema:
          type: integer
          default: 1
          example: 1
    responses:
      '200':
        description: Successful response
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: array
                  items:
                    $ref: '../components/schemas.yml#/ProductList'
                current_page:
                  type: integer
                  example: 1
                last_page:
                  type: integer
                  example: 5
                per_page:
                  type: integer
                  example: 15
                total:
                  type: integer
                  example: 75
                first_page_url:
                  type: string
                  example: http://localhost:8000/api/products?page=1
                last_page_url:
                  type: string
                  example: http://localhost:8000/api/products?page=5
                next_page_url:
                  type: string
                  nullable: true
                  example: http://localhost:8000/api/products?page=2
                prev_page_url:
                  type: string
                  nullable: true
                  example: null
                path:
                  type: string
                  example: http://localhost:8000/api/products
                from:
                  type: integer
                  example: 1
                to:
                  type: integer
                  example: 15

product:
  get:
    tags:
      - Products
    summary: Get product details
    description: Get detailed information about a specific product including reviews
    operationId: getProduct
    parameters:
      - name: id
        in: path
        description: Product ID
        required: true
        schema:
          type: integer
          example: 1
    responses:
      '200':
        description: Successful response
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  $ref: '../components/schemas.yml#/ProductDetail'
      '404':
        $ref: '../components/responses.yml#/NotFound'
